### ISSUE TITLE
Windows下被调用时出现[FEKit_]error字段

### ISSUE THREAD

**Issue by TinQlo** [fuqiuluo/unidbg-fetch-qsign#10]
更新描述指令部分，将星号改为xxx   

小描述：
Windows下被调用时出现[FEKit_]error字段。被签名应用和unidbg-fetch-qsign都可以正常运行，没有报错和跳出，但不清楚有无签名成功

一些信息：
1.0.4 JAR版本
Windows 11下使用bat运行，指令为   xxxxx/unidbg-fetch-qsign-1.0.4/bin/unidbg-fetch-qsign.bat --port=xxx  --count=1 --library=xxx\unidbg-fetch-qsign-1.0.4\bin\lbis --android_id=xxxxxxxxxxxxx

部分log截图，请注意123行处（由于不知道用处，十六进制数字被我用xxx代替）
![image](https://github.com/fuqiuluo/unidbg-fetch-qsign/assets/30965687/4f196495-63f4-4837-8714-280af4959318)  

完整log请见  
[[FEKit_]error的cmd窗口log.txt](https://github.com/fuqiuluo/unidbg-fetch-qsign/files/11883312/FEKit_.error.cmd.log.txt)

**Comment by SunshineboyZj** [comment]
这个影响使用（go-cqhttp登上去，发送消息）吗

**Comment by TinQlo** [comment]
> 这个影响使用（go-cqhttp登上去，发送消息）吗
应该有签名成功，也不影响使用  
问题：  
使用go-cqhttp协议2（安卓手表）登录并签名的实例在运行一会儿后惨遭风控，只能看不能发。
解决方法：  
更改了一下QQ密码，之后在go-cqhttp的config.yml中协议改为了1（安卓手机），先前没有签名的时候，协议1无论怎样都会无法登陆（代码45还是43忘记了，总之版本过低请升级QQ）。但有了签名后经过了拉验证码长条和短信验证，可以正常登陆并且风控状态消失。

**Comment by SunshineboyZj** [comment]
嗯，不影响，刚才我拿大号试了下，可以登上去并正常发消息



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月27日(周二) 晚上10:52
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [fuqiuluo/unidbg-fetch-qsign] Windows下被调用时出现[FEKit_]error字段 (Issue #10)




  
这个影响使用（go-cqhttp登上去，发送消息）吗
 应该有签名成功，也不影响使用
 问题：
 使用go-cqhttp协议2（安卓手表）登录并签名的实例在运行一会儿后惨遭风控，只能看不能发。
 解决方法：
 更改了一下QQ密码，之后在go-cqhttp的config.yml中协议改为了1（安卓手机），先前没有签名的时候，协议1无论怎样都会无法登陆（代码45还是43忘记了，总之版本过低请升级QQ）。但有了签名后经过了拉验证码长条和短信验证，可以正常登陆并且风控状态消失。

**Comment by fuqiuluo** [comment]
错误可无视
