### ISSUE TITLE
[2023-07-06 16:43:03] [WARNING]: 获取T544 sign时出现错误: encoding/hex: invalid byte: U+0069 'i'

### ISSUE THREAD

**Issue by kumu7y** [fuqiuluo/unidbg-fetch-qsign#104]
![image](https://github.com/fuqiuluo/unidbg-fetch-qsign/assets/85327198/0e34de5f-f94b-4d46-bf39-26f3a2836921)
运行后调用sign报错

**Comment by AreCie** [comment]
同样问题，请问你说怎么解决的？

**Comment by kumu7y** [comment]
> 同样问题，请问你说怎么解决的？

使用1.1.0版本，或者等cq适配

**Comment by AreCie** [comment]
> > 同样问题，请问你说怎么解决的？
> 
> 使用1.1.0版本，或者等cq适配

好的，我降下级试试，谢谢！
