### ISSUE TITLE
登录成功，号被冻结

### ISSUE THREAD

**Issue by qinjianwei** [fuqiuluo/unidbg-fetch-qsign#106]
## 问题咨询、讨论，请在 [Discussions](../discussions) 发帖。issues 仅用于提交 Bug。

**Comment by SunshineboyZj** [comment]
这你得问tx。我第一次用签名也被冻了，解了之后号活到现在

**Comment by ilihu** [comment]
其实，如果用官方客户端正常登录。是不会冻结的

**Comment by SunshineboyZj** [comment]
> 这你得问tx。我第一次用签名也被冻了，解了之后号活到现在

又被冻了。。。
