### ISSUE TITLE
报错缺少android_id

### ISSUE THREAD

**Issue by TsaiDuck** [fuqiuluo/unidbg-fetch-qsign#11]
PS C:\Users\Administrator\Desktop\qsign\unidbg-fetch-qsign-1.0.4> bin/unidbg-fetch-qsign --port=8080  --count=1 --library=txlib/8.9.63
Exception in thread "main" java.lang.IllegalArgumentException: Lack of android_id
        at moe.fuqiuluo.comm.ArgsParser.get(ArgsParser.kt:25)
        at MainKt.main(Main.kt:53)
PS C:\Users\Administrator\Desktop\qsign\unidbg-fetch-qsign-1.0.4> java -version
java version "1.8.0_351"
Java(TM) SE Runtime Environment (build 1.8.0_351-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.351-b10, mixed mode)
PS C:\Users\Administrator\Desktop\qsign\unidbg-fetch-qsign-1.0.4>

**Comment by TinQlo** [comment]
我看你的指令里没有指定android_id，假如你用了go-cqhttp，android_id可以在你的device.json中找到
