### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by Yvan-W** [fuqiuluo/unidbg-fetch-qsign#117]
![图片](https://github.com/fuqiuluo/unidbg-fetch-qsign/assets/80970174/2c879e7b-4525-48a7-b9b8-d4c92c2bdcb5)
系统环境 Ubuntu 22.0.4 LTS x64
Azure 虚拟机
参考教程 Linux部署教程
命令：/root/unidbg-fetch-qsign-1.1.0/bin/unidbg-fetch-qsign --host=127.0.0.1 --port=8901 --count=2 --library=/root/unidbg-fetch-qsign-1.1.0/txlib/8.9.63 --android_id=acc6fdf5db4459c2

**Comment by Yvan-W** [comment]
命令：/root/unidbg-fetch-qsign-1.1.0/bin/unidbg-fetch-qsign --host=127.0.0.1 --port=8901  --count=2 --library=/root/unidbg-fetch-qsign-1.1.0/txlib/8.9.63  --android_id=acc6fdf5db4459c2

**Comment by YingLing3** [comment]
该错误可以忽略，gocq那边能正常发消息就行了

**Comment by Yvan-W** [comment]
> 该错误可以忽略，gocq那边能正常发消息就行了

行，我试试
