### ISSUE TITLE
使用80分钟后，调用时会timeout

### ISSUE THREAD

**Issue by Starlwr** [fuqiuluo/unidbg-fetch-qsign#120]
使用 mirai 的 fix-protocol-version 1.9.4 配合最新版的签名服务 1.1.3，可以正常登录并发送消息，但每次运行80分钟左右以后，调用签名服务会超时，重启 mirai 后即可恢复正常，可以再次使用80分钟，最初以为是 fix-protocol-version 的问题，经过在那边的讨论，问题应该出在这里：https://github.com/cssxsh/fix-protocol-version/discussions/45

**Comment by MrY-Cat** [comment]
确实，1.1.3很稳定的timeOut

**Comment by fuqiuluo** [comment]
```/request_token```未经过充足的调试，导致出现这个问题，将加入超时机制，重制会话刷新token。

**Comment by zhiyf** [comment]
您好，我想问一下2023-07-16 04:00:01 V/Bot.1635259451: Event: BotOfflineEvent.Active(bot=Bot(1635259451), cause=null, reconnect=false)
这个是什么情况，每次运行一两天就会自动掉线
