### ISSUE TITLE
计算期间cpu100%，需要40秒才能返回结果，导致客户端超时。

### ISSUE THREAD

**Issue by icerxkx** [fuqiuluo/unidbg-fetch-qsign#131]
## 问题咨询、讨论，请在 [Discussions](../discussions) 发帖。issues 仅用于提交 Bug。
ubuntu系统，接受登录请求时cpu java进程持续100%近40秒才能降下来，然后返回结果

**Comment by fuqiuluo** [comment]
你CPU是单核？

**Comment by jinyu2022** [comment]
> 你CPU是单核？

1vcpu的服务器吧
