### ISSUE TITLE
docker方式启动后容器一直重启，log中提示JAVA环境变量设置有误

### ISSUE THREAD

**Issue by avadiana** [fuqiuluo/unidbg-fetch-qsign#16]
使用docker run -d --restart=always --name qsign -p 8080:8080 -e ANDROID_ID=8648b45f697891b4 xzhouqd/qsign:8.9.63启动镜像后，
![image](https://github.com/fuqiuluo/unidbg-fetch-qsign/assets/88984346/5171316c-fb86-41ac-b56c-b70608bb88b9)
容器镜像一直在不停重启，然后使用“docker container logs qsign”命令查看log，log的报错为：
“Using port 8080, count 1, android_id 8648b45f697891b4
ERROR: JAVA_HOME is set to an invalid directory: /opt/java/openjdk
Please set the JAVA_HOME variable in your environment to match the location of your Java installation.”
![image](https://github.com/fuqiuluo/unidbg-fetch-qsign/assets/88984346/de5d93ac-5a1d-40ed-b952-d105c2aec3d3)
请问这是docker的镜像存在问题吗，还是我的机子配置有问题呢？

**Comment by avadiana** [comment]
好像还真是我这台机子的问题，在另外一台机子上就能正常启动镜像了

**Comment by XZhouQD** [comment]
升级下docker engine版本试试？从我收集的信息来看，是eclipse temurin jdk的底包版本很高，docker engine老的话会有这个问题。[adoptinum/containers:#215](https://github.com/adoptium/containers/issues/215)

**Comment by avadiana** [comment]
感谢您的解答，我这边看了下我这台机子得docker engine版本确实是比较久的，我过两天尝试升级一下看看能否解决该问题，感谢您
