### ISSUE TITLE
1.1.7 qsign 刷新 token 出现错误: code=1, msg: This mutex is not locked

### ISSUE THREAD

**Issue by dfmjndm** [fuqiuluo/unidbg-fetch-qsign#202]
[0m[37m[2023-08-12 15:58:18] [INFO]: 正在刷新 token 
[0m[33m[2023-08-12 15:58:23] [WARNING]: 刷新 token 出现错误: code=1, msg: This mutex is not locked. server:  http://××××××××

docker版1.1.7qsign，相同情况见 https://github.com/Mrs4s/go-cqhttp/issues/2347

**Comment by qn8524king** [comment]
我也遇到了，windows下好像是没问题的

**Comment by TNCNET** [comment]
+1
qsign是1.1.7，不过是icqq（0.5.1）+8.9.73
出现错误后icqq端提示45错误，多次尝试无效。
