### ISSUE TITLE
脚 本 寄 了

### ISSUE THREAD

**Issue by Mubanjun** [fuqiuluo/unidbg-fetch-qsign#208]
openjdk19，寄了，咋搞![1691851563626.jpg](https://github.com/fuqiuluo/unidbg-fetch-qsign/assets/110292675/b61effa4-6fb7-44e4-9507-c188202b9040)

![Screenshot_2023-08-14-08-28-35-26_8659c1e795b4b4239e38d87c88c077b3.jpg](https://github.com/fuqiuluo/unidbg-fetch-qsign/assets/110292675/37746f42-ffa0-4427-8092-04ed4ac4e75d)

**Comment by Dream-Rainy** [comment]
wiki中有提到

> 系统安装jdk或者jre，版本1.8或以上。如果报错找不到类，请尝试1.8或略靠近1.8的版本

可以试试降低版本

**Comment by xiangxiangxiong9** [comment]
> 括号改双分号改完了，这回又丢出来个函数错误，jdk版本有限制吗？

把脚本里的第35行到40行发出来看看？
_感觉是shell语法有问题[?]_

**Comment by callng** [comment]
> 把脚本里的第35行到40行发出来看看？ _感觉是shell语法有问题[?]_

[1.1.7](https://github.com/fuqiuluo/unidbg-fetch-qsign/releases/tag/1.1.7) 这里，看看吧 我也不知道是怎么回事。

**Comment by xiangxiangxiong9** [comment]
怪欸[无法复现于 Ubuntu 23.04]

**Comment by DiamondHunters** [comment]
项目是直接git clone进去的嘛？shell程序使用的是bash嘛？

**Comment by DiamondHunters** [comment]
> > 项目是直接git clone进去的嘛？shell程序使用的是bash嘛？
> 
> sh直接运行的，脚本用火狐开Github下载的

使用bash即可

**Comment by xiangxiangxiong9** [comment]
Termux?
Termux套容器[proot/chroot]不支持systemd好像
[chroot 好像是 Running in chroot, ignoring request.]

**Comment by DiamondHunters** [comment]
> ![1692012760408.jpg](https://user-images.githubusercontent.com/110292675/261262939-abe67bd3-e97f-4d36-b5ab-56d4576f3c69.jpg)
> 
> ![2023_08_17 17_23 Office Lens.jpg](https://user-images.githubusercontent.com/110292675/261263157-bda6d55f-ba57-448b-9ba7-d6db6391c305.jpg)

是否具有真root权限并且启用了systemd？如果不是的话就手动运行吧

**Comment by DiamondHunters** [comment]
> > > ![1692012760408.jpg](https://user-images.githubusercontent.com/110292675/261262939-abe67bd3-e97f-4d36-b5ab-56d4576f3c69.jpg)
> > > ![2023_08_17 17_23 Office Lens.jpg](https://user-images.githubusercontent.com/110292675/261263157-bda6d55f-ba57-448b-9ba7-d6db6391c305.jpg)
> > 
> > 
> > 是否具有真root权限并且启用了systemd？如果不是的话就手动运行吧
> > 可是我是安卓诶$_$所以那个给安卓用的SignFaker咋用，说明太少了

如果想按照linux方式部署则不要使用脚本内以服务运行的方式，手动使用命令启动即可

**Comment by callng** [comment]
更新了[Wiki](https://github.com/fuqiuluo/unidbg-fetch-qsign/wiki/%E9%83%A8%E7%BD%B2%E5%9C%A8Linux#%E5%90%8E%E5%8F%B0%E8%BF%90%E8%A1%8C--%E8%87%AA%E5%90%AF%E5%8A%A8stemd)
