### ISSUE TITLE
佬，我的systemd启动一直报这个怎么解决？

### ISSUE THREAD

**Issue by Control-Exalt** [fuqiuluo/unidbg-fetch-qsign#212]
Aug 15 19:20:21 VM-8-13-centos systemd[1]: [/etc/systemd/system/qsign.service:8] Executable path is not absolute, ignoring: bash bin/unidbg-fetch-qsign --basePath=txlib/8.9.68
Aug 15 19:20:21 VM-8-13-centos systemd[1]: qsign.service lacks both ExecStart= and ExecStop= setting. Refusing.
Aug 15 19:20:31 VM-8-13-centos systemd[1]: [/etc/systemd/system/qsign.service:8] Executable path is not absolute, ignoring: bash bin/unidbg-fetch-qsign --basePath=txlib/8.9.68
Aug 15 19:20:31 VM-8-13-centos systemd[1]: qsign.service lacks both ExecStart= and ExecStop= setting. Refusing.

**Comment by huanlin690** [comment]
> 那个，ExecStart=后面的路径要写绝对路径，以`/`开头。 建议改成`/bin/unidbg-fetch-qsign --basePath=/bin/unidbg-fetch-qsign/txlib/8.9.68`，bash前缀可以不加（ 啊，怎么经常改完了才发现写错了（

谢谢！解决了
