### ISSUE TITLE
不明报错，并不影响使用，但是可能会导致意外崩溃

### ISSUE THREAD

**Issue by Neko-Yukari** [fuqiuluo/unidbg-fetch-qsign#218]
unidbg-fetch-qsign-onekey Ver.1.1.7
txlib_Version is 8.9.70
If you want to change txlib_version , please delete [txlib_version.json]
---------------------------------------------------------------
The config file already contains account information.
---------------------------------------------------------------
Qsign API:http://127.0.0.1:13579
KEY=1145141919810
Qsign_version:1.1.7
TXlib_version:8.9.70
---------------------------------------------------------------
FEBond sum = 7680
22:47:13.664 [main] INFO ktor.application - Autoreload is disabled because the development mode is off.
22:47:13.977 [main] INFO ktor.application - Application started in 0.345 seconds.
22:47:13.977 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
22:47:14.009 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
22:47:14.009 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 11
22:47:14.009 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
22:47:14.009 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
22:47:14.009 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.storeFence: available
22:47:14.009 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
22:47:14.009 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: unavailable: Reflective setAccessible(true) disabled
22:47:14.009 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
22:47:14.009 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable: class io.netty.util.internal.PlatformDependent0$7 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @c54a56
22:47:14.024 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): unavailable
22:47:14.024 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
22:47:14.024 [main] DEBUG io.netty.util.internal.PlatformDependent - maxDirectMemory: 259522560 bytes (maybe)
22:47:14.024 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: C:\Users\ADMINI~1\AppData\Local\Temp\1 (java.io.tmpdir)
22:47:14.024 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 32 (sun.arch.data.model)
22:47:14.040 [main] DEBUG io.netty.util.internal.PlatformDependent - Platform: Windows
22:47:14.040 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: -1 bytes
22:47:14.040 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
22:47:14.040 [main] DEBUG io.netty.util.internal.CleanerJava9 - java.nio.ByteBuffer.cleaner(): available
22:47:14.040 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
22:47:14.102 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 8
22:47:14.118 [main] DEBUG io.netty.util.concurrent.GlobalEventExecutor - -Dio.netty.globalEventExecutor.quietPeriodSeconds: 1
22:47:14.118 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
22:47:14.118 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
22:47:14.118 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
22:47:14.118 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
22:47:14.133 [main] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
22:47:14.149 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 1028 (auto-detected)
22:47:14.149 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
22:47:14.149 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
22:47:14.197 [main] DEBUG io.netty.util.NetUtilInitializations - Loopback interface: lo (Software Loopback Interface 1, 127.0.0.1)
22:47:14.197 [main] DEBUG io.netty.util.NetUtil - Failed to get SOMAXCONN from sysctl and file \proc\sys\net\core\somaxconn. Default: 200
22:47:14.197 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: 00:e1:4f:ff:fe:68:13:15 (auto-detected)
22:47:14.213 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
22:47:14.213 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.targetRecords: 4
22:47:14.228 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 8
22:47:14.228 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 8
22:47:14.228 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
22:47:14.228 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 9
22:47:14.228 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 4194304
22:47:14.228 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
22:47:14.228 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
22:47:14.228 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
22:47:14.228 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
22:47:14.228 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimIntervalMillis: 0
22:47:14.228 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: false
22:47:14.228 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
22:47:14.228 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
22:47:14.228 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 0
22:47:14.228 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
22:47:14.244 [DefaultDispatcher-worker-1] INFO ktor.application - Responding at http://127.0.0.1:13579
22:47:18.040 [eventLoopGroupProxy-3-1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkAccessible: true
22:47:18.040 [eventLoopGroupProxy-3-1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkBounds: true
22:47:18.056 [eventLoopGroupProxy-3-1] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@4c5f1c
22:47:18.087 [eventLoopGroupProxy-3-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 4096
22:47:18.087 [eventLoopGroupProxy-3-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
22:47:18.087 [eventLoopGroupProxy-3-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.chunkSize: 32
22:47:18.102 [eventLoopGroupProxy-3-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.blocking: false
22:47:18.102 [eventLoopGroupProxy-3-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.batchFastThreadLocalOnly: true
22:47:18.149 [eventLoopGroupProxy-4-1] DEBUG org.scijava.nativelib.BaseJniExtractor - Deleting leftover folder: C:\Users\ADMINI~1\AppData\Local\Temp\1\nativelib-loader_1289626451540027880
22:47:18.149 [eventLoopGroupProxy-4-1] DEBUG org.scijava.nativelib.BaseJniExtractor - Deleting leftover folder: C:\Users\ADMINI~1\AppData\Local\Temp\1\nativelib-loader_1354769977542190372
22:47:18.149 [eventLoopGroupProxy-4-1] DEBUG org.scijava.nativelib.BaseJniExtractor - Deleting leftover folder: C:\Users\ADMINI~1\AppData\Local\Temp\1\nativelib-loader_2514439046628432933
22:47:18.165 [eventLoopGroupProxy-4-1] DEBUG org.scijava.nativelib.NativeLibraryUtil - processor is INTEL_32 os.arch is x86
22:47:18.165 [eventLoopGroupProxy-4-1] DEBUG org.scijava.nativelib.NativeLibraryUtil - architecture is WINDOWS_32 os.name is windows server 2019
22:47:18.165 [eventLoopGroupProxy-4-1] DEBUG org.scijava.nativelib.NativeLibraryUtil - architecture is WINDOWS_32 os.name is windows server 2019
22:47:18.165 [eventLoopGroupProxy-4-1] DEBUG org.scijava.nativelib.NativeLibraryUtil - platform specific path is natives/windows_32/
22:47:18.165 [eventLoopGroupProxy-4-1] DEBUG org.scijava.nativelib.BaseJniExtractor - mappedLib is unicorn.dll
22:47:18.165 [eventLoopGroupProxy-4-1] DEBUG org.scijava.nativelib.BaseJniExtractor - Couldn't find resource natives/windows_32/unicorn.dll
22:47:18.165 [eventLoopGroupProxy-4-1] DEBUG org.scijava.nativelib.NativeLibraryUtil - platform specific path is windows_32/
22:47:18.165 [eventLoopGroupProxy-4-1] DEBUG org.scijava.nativelib.BaseJniExtractor - mappedLib is unicorn.dll
22:47:18.165 [eventLoopGroupProxy-4-1] DEBUG org.scijava.nativelib.BaseJniExtractor - Couldn't find resource windows_32/unicorn.dll
22:47:18.165 [eventLoopGroupProxy-4-1] DEBUG org.scijava.nativelib.NativeLibraryUtil - platform specific path is META-INF/lib/windows_32/
22:47:18.165 [eventLoopGroupProxy-4-1] DEBUG org.scijava.nativelib.BaseJniExtractor - mappedLib is unicorn.dll
22:47:18.165 [eventLoopGroupProxy-4-1] DEBUG org.scijava.nativelib.BaseJniExtractor - Couldn't find resource META-INF/lib/windows_32/unicorn.dll
22:47:18.212 [eventLoopGroupProxy-4-1] DEBUG org.scijava.nativelib.NativeLibraryUtil - architecture is WINDOWS_32 os.name is windows server 2019
22:47:18.212 [eventLoopGroupProxy-4-1] DEBUG org.scijava.nativelib.NativeLibraryUtil - platform specific path is natives/windows_32/
22:47:18.212 [eventLoopGroupProxy-4-1] DEBUG org.scijava.nativelib.BaseJniExtractor - mappedLib is unicorn_java.dll
22:47:18.212 [eventLoopGroupProxy-4-1] DEBUG org.scijava.nativelib.BaseJniExtractor - URL is jar:file:/C:/Users/Administrator/Desktop/Everything%20of%20dice/qsign1.1.7-txlib_8.9.70/lib/unidbg-1.0.3.jar!/natives/windows_32/unicorn_java.dll
22:47:18.212 [eventLoopGroupProxy-4-1] DEBUG org.scijava.nativelib.BaseJniExtractor - URL path is file:/C:/Users/Administrator/Desktop/Everything%20of%20dice/qsign1.1.7-txlib_8.9.70/lib/unidbg-1.0.3.jar!/natives/windows_32/unicorn_java.dll
22:47:18.212 [eventLoopGroupProxy-4-1] DEBUG org.scijava.nativelib.BaseJniExtractor - Extracting 'jar:file:/C:/Users/Administrator/Desktop/Everything%20of%20dice/qsign1.1.7-txlib_8.9.70/lib/unidbg-1.0.3.jar!/natives/windows_32/unicorn_java.dll' to 'C:\Users\ADMINI~1\AppData\Local\Temp\1\nativelib-loader_3203608765475938466\unicorn_java.dll'
[FEKit_]info: device_token_entry.h:88 initUin 2224691413
[FEKit_]info: device_info.h:586 start create xwid
[FEKit_]info: device_info.h:613 create xwid complete
[FEKit_]error: device_token_storage.h:53 write file error
[FEKit_]info: device_token.h:345 create new xwId complete
[FEKit_]error: o3_channel_encrypt.h:275 gen new channel
FEBound.transform(c84e70d8a31b5e9398d8878aa829c4b7ceaee392f738fdfa263bd744d9d2d91e) => e595824bb273848d808529cb9edc45c0e035c9d0476d682c1ebc89d0557d3af6
[FEKit_]error: o3_channel_encrypt.h:491 est check: 1d13036215b269e12c691bc8697ec622cb5e6410712b596776e4bad771be901da671270d8e1468f42577b56b2b16b078
[FEKit_]error: ChannelManager.cpp:73 o3cm@S: GetSecConf, trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish
uin = 2224691413, id = 0, sendPacket(cmd = trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish, data = 0a0a476574536563436f6e66122103df18631a44828d93128cf69b9c7cdb225eda4afe9b33a26c6a118589cd7f577e22423833633536323337366539323963626161353837383730666262373264386337663363666539373731646631343830386562333061613931373932336664643563652a49405703e14b987cb7f5b1f3aee4fac1a610f96b5b788877795fcc3ea2cfed51a87f25810ade7fd7773177056d6deaae986689f1137fad7929cc22e4725a1fbdde09739d0bc6bb46f2683220e8c855205b3d5b0ff0e921c9eb195a51b32d617904c019932fa0f2a80eeb0b1d3a301d13036215b269e12c691bc8697ec622cb5e6410712b596776e4bad771be901da671270d8e1468f42577b56b2b16b0784001)
[FEKit_]error: o3_channel_encrypt.h:442 ecdh repeat establish
FEBound.transform(5f0264b3d5ca15d5fe0d238a3c0a40c0b7f008fe8c66ced80f76b2c75e2da609) => 5fa27351eff6becb39094bcbffb5f37d2627588521e474c85beff09e12d4b108
[FEKit_]error: o3_channel_encrypt.h:491 est check: fd18a439ef03fa9128cb0a985e040304fb7030bcf95edd5f833717b3ddde166c0f1067c638ac7fc0729a3c61506a0246
[FEKit_]error: ChannelManager.cpp:73 o3cm@S: O3GetTail, trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish
uin = 2224691413, id = 1, sendPacket(cmd = trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish, data = 0a094f334765745461696c122103df18631a44828d93128cf69b9c7cdb225eda4afe9b33a26c6a118589cd7f577e22423833633536323337366539323963626161353837383730666262373264386337663363666539373731646631343830386562333061613931373932336664643563652a493d27fc3464e5a5a32c258fe4037a5952f3a9155cfc56f9a6565d06a756b1f3f8f3584f231efcec5432db2ac71619dd09611219a09349e3b2168c8db96accc2f06f50b57ddd6da33cf43220e8c855205b3d5b0ff0e921c9eb195a51b32d617904c019932fa0f2a80eeb0b1d3a30fd18a439ef03fa9128cb0a985e040304fb7030bcf95edd5f833717b3ddde166c0f1067c638ac7fc0729a3c61506a02464001)
[FEKit_]error: device_info.h:178 jniGetAppVersionName:8.9.70
[FEKit_]info: device_info.h:538 538
[FEKit_]info: device_info.h:540 540
[FEKit_]info: device_info.h:542 542
[FEKit_]info: device_token.h:235 begin pack
[FEKit_]info: device_token.h:237 pack buff result len:1180
[FEKit_]info: device_token.h:252 begin sendmessage : len :1180
[FEKit_]error: o3_channel_encrypt.h:442 ecdh repeat establish
FEBound.transform(1eace113cff2b8e03d0d78ba9067150d44eb7ae5883a9161f24c71d5602f0cc8) => a03dc5c1db4cf347cf095a4b2d66280c0ed68a9a2666419e36ae5de53dd26f7e
[FEKit_]error: o3_channel_encrypt.h:491 est check: c308678ef64ed83262569680fbcae8ef7eeb48b220e17441a7b6475934395fe267318635a394e9de2db3da5b6e8f8aaf
[FEKit_]error: ChannelManager.cpp:73 o3cm@S: getToken, trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish
uin = 2224691413, id = 2, sendPacket(cmd = trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish, data = 0a08676574546f6b656e122103df18631a44828d93128cf69b9c7cdb225eda4afe9b33a26c6a118589cd7f577e22423833633536323337366539323963626161353837383730666262373264386337663363666539373731646631343830386562333061613931373932336664643563652ae8091960f3e390a674955acc6c1cacc6591ed8bb4abf2da0b234a78718f6eb07db23e6fc4b4c67bac54a949d89df514f88669a8d392d41fb1ed7315cac2311ba9df329a86ee81903db03b168e87a2fcbbec0d730bf8330ad8a7cfa7f9e7d86be5aaf90d165c6effda99245201e9149d8ab7211343fce318140f2df916812ebbb3e99033c2df674bfbd5d47ae9e270db11dcd082a5243002ca515efa26e2d93d7a4fc6c2c5b77e63bb4d7a356a82208cf6f6a124d64c8770fcf7e5a1d47ec183e28f6b0f190c9d2b580b48e827c58c6dbebfb21493a666f61da4c0a6ab14edf23b72fe3bf9be1a4dedaaba7be6b7856d8bb8dc4bbaf3962df2ac0ea9bf8248a1e775de60907d6e0c1b9db8ff215782f46a74cbde961ea5c4fe8aa912827cec6de40002208ba27af0de804331f62e1afb59968db25ade68d69ef366cb494e912c35d1690a4e3978108818d7374b0afda11c62ee70468320f428e47326e344852f629e67c2f53b9cafa8f4e66ff350038dca8dda7f253a0b59e5e94a51ddb49a1a41073db3cec31367e7a78c4403ad2959cf6985597cc5e87bfbd3e1841eff87acd7a2d0f34565c1881c42916902671e47e7f135ea94cac5ab2046e8df0ddd619f456359fb4a5efc3cd9c5cbf35653d8d6da762047dd90ac9055404e0f8aa4a6568e3ab7f9484899aeb879b9de4bc58f50fc24373e7673b2aa41965645895691e84bcbe70ab6c071029cf028e7e931d143c25eb00fdae6522a3ec075e00362db70f00e75da939b4a0ce2be6315a9b1f52801457616d041819e4d2027cedb4e722f40aec54aadd26745fee589894f056f8235bf2e7a9f9962d3584624dd69b573ae540662ecea1a6fccae1c687bcb97ee2c56a6a1c5da7e5e09e42206287ce78df78a76e4a75ab7c762c5f24bb3b2e8175cfeff3a18daaae36874bdf9b87e7b41c22bc109f5a6587c9df622a150554cf331eca2b732a7a38966c98d8be2e4e563d713a53d84e049b075c317229416d5b085db90bcf7ca5c6887ef0e54e339a5a4005c556b871d1fb6a8b8a2555d3d12491fc0f0f2bd36782097fffc45bea3a1e87d65c949fa7ea5a6c7fc9b4efa3a47be92fc9cc904781b96753db62d7db6a623a468970196e81c8fe658edc3c939be7b9c43549416d64e65bbbedef7ac2a4d9aa890c26d46bc09a3e89e86029a602359f3e207c4371580eac3ead5ddd865ef34db4f2d93d5b2d6e0d66d5b9d75985746c01e7d13143f769ff0df133a621134b6a45e98a8cfb4b5c4e6d4e8bb0d088932be4e58e6c6f7e5a65d53d246e8dabbc6b7f2cbeba8f2e80d071e1857a983c039c7ed86d07cf4261f7bace13d3319865ee33cfbe5dd9f52bb2176a178be4141b996ad3d32d8cbe741bbea8f96a98a1f9339bab33fd5ce786ffc258479f332df602d55bd064e10000a2cf57c03dc015d4e206eb759ad20d3e23e3c8ad17b5a6f788f8df77a7ca70355e8605edc6c0905ca8602de342c8b995eb0dbb6834893dff2e616cd6dfef13325a5da756ee8e0b670752023837bb7c17c66f3c404584cfc298ed5799d7a32280700385f78f5182b6640a3437592b6f9b31ea9e4c0a344c9e734f51b3bfcf9175f03c442664d5ad871640a264ac459f7f1db4b2a4a04ff4ed900d765459fad433a0c996cdbb5e8a853bbfaf2e1f803a54b097955ac7b3a095f249fe9e2373cd87c6342de3474080834ca4666caca11e963d2ae81c4f88f933547d96cd43456ccb54c943200b704d75ff3330154d9fb4c2a5f5faa83220e8c855205b3d5b0ff0e921c9eb195a51b32d617904c019932fa0f2a80eeb0b1d3a30c308678ef64ed83262569680fbcae8ef7eeb48b220e17441a7b6475934395fe267318635a394e9de2db3da5b6e8f8aaf4001)
[FEKit_]info: qq_sign.h:142 [GetSign] cmd:wtlogin.exchange_emp
FEBound.transform(421acb1102da382acdd90104000000000200030000e04040095f84b48036f7d3e7000000004865726f) => 0d5994c2a4b6335cdf82bd500db8630dfda759fda882cd075c5124408d50075796a752fda80deed54b
[FEKit_]info: ChannelManager.cpp:98 origin cmd:GetSecConf ,cmd:trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish
[FEKit_]error: ChannelManager.cpp:101 [ChannelManager:OnReceive] success:1 cmd:trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish bcmd:GetSecConf
[FEKit_]error: o3_channel_encrypt.h:579 dec non-zero retcode: 33
[FEKit_]error: o3_channel_encrypt.h:204 channel reset
[FEKit_]error: ChannelManager.cpp:148 [ChannelManager:OnReceive] cryptError 2000
[FEKit_]error: dynamic_config_manager.h:33 get SecConfig failed
[FEKit_]info: ChannelManager.cpp:98 origin cmd:O3GetTail ,cmd:trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish
[FEKit_]error: ChannelManager.cpp:101 [ChannelManager:OnReceive] success:1 cmd:trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish bcmd:O3GetTail
[FEKit_]error: o3_channel_encrypt.h:537 est rsp after reset
[FEKit_]error: sign_tail_manager.h:79 get tail success 1, retCode 0
[FEKit_]error: o3_channel_encrypt.h:275 gen new channel
FEBound.transform(e1bbf012280ae7daf570e69af10ff2a3de12d6f6cb53418840bf8ff385cebc24) => 91f6e2c076561bcc33edc38b44b202a76052ab84d021c1e8a22122768729df62
[FEKit_]error: o3_channel_encrypt.h:491 est check: 38589ef0fdcbeb3c42069d14d45a41ecd5c93b4281e1f76e8191d87bdedb5d17f82b666d00b03996a133571c92f70fe3
[FEKit_]error: ChannelManager.cpp:73 o3cm@S: O3GetTail, trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish
uin = 2224691413, id = 3, sendPacket(cmd = trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish, data = 0a094f334765745461696c122102bcf68674701987557494259e4b7790632bfb846e2fb3ba374da14891395e016922423833633536323337366539323963626161353837383730666262373264386337663363666539373731646631343830386562333061613931373932336664643563652a48c251a624ed3f628c84de5a652ddf30ff654a34125d88b82754f40ef5c3c45e0514572204efb26fc6a7a7a343980aab88981f3e2bd051e08dc74df2dc6a5ccabe1672dadf5c9ec5b4322081d79e90028745c26d102d12c02dd454c1e9369877b7bda1562b97c503582ef63a3038589ef0fdcbeb3c42069d14d45a41ecd5c93b4281e1f76e8191d87bdedb5d17f82b666d00b03996a133571c92f70fe34001)
[FEKit_]info: ChannelManager.cpp:98 origin cmd:getToken ,cmd:trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish
[FEKit_]error: ChannelManager.cpp:101 [ChannelManager:OnReceive] success:1 cmd:trpc.o3.ecdh_access.EcdhAccess.SsoSecureA2Establish bcmd:getToken
[FEKit_]error: o3_channel_encrypt.h:544 ESK pb de failed
[FEKit_]error: ChannelManager.cpp:148 [ChannelManager:OnReceive] cryptError 1
[FEKit_]info: device_token.h:274 response len :0
[FEKit_]error: device_token.h:278 get token error! errorcode:1,mFailedTimes:1
接入gocqhttp时会就出现这种错误，但并不影响接入的骰子正常使用命令，我用的是dicePP，每次使用指令时也会出现这种带有长串字符串的错误。
当挂机过久后整个cmd会直接崩掉
服务器是winserver2019，gocqhttp版本8ac00f6，qsign版本1.1.7，txlib版本8.9.70，jdk版本1.8.0_321

**Comment by rhwong** [comment]
8ac00f6的问题
换新的go-cqhttp的action

**Comment by Neko-Yukari** [comment]
> 8ac00f6的问题 换新的go-cqhttp的action

问题已解决，谢谢解答

**Comment by Neko-Yukari** [comment]
好了，换了最新的gocq搞定了（）
