### ISSUE TITLE
找不到 bin/unidbg-fetch-qsign 文件

### ISSUE THREAD

**Issue by HelenWu99** [fuqiuluo/unidbg-fetch-qsign#222]
根据命令`bash bin/unidbg-fetch-qsign --basePath=txlib/8.9.68`启动，但是提示：**bash: bin/unidbg-fetch-qsign: No such file or directory**
看了code的目录，确实没有看到bin目录，请问在哪儿获取bin文件夹呢？

**Comment by callng** [comment]
在releases下载编译好的，而不是直接下载源代码。
