### ISSUE TITLE
Linux执行启动命令提示Could not find or load main class MainKt

### ISSUE THREAD

**Issue by tianyisama** [fuqiuluo/unidbg-fetch-qsign#251]
## 问题咨询、讨论，请在 [Discussions](../discussions) 发帖。issues 仅用于提交 Bug。
版本为1.2.1，系统为centos8，Java版本为java-1.8.0-openjdk.x86_64，执行bash bin/unidbg-fetch-qsign --basePath=txlib/8.9.73时提示Could not find or load main class MainKt，无任何其他报错信息，使用1.1.9版本及其以下的签名均没有任何问题

**Comment by callng** [comment]
请重新下载1.2.1版本
