### ISSUE TITLE
config.json 中若未配置新增的参数会报错

### ISSUE THREAD

**Issue by gebederry** [fuqiuluo/unidbg-fetch-qsign#252]
版本: V1.2.1
问题描述: 
在 V1.2.1 中强制新增了几个参数，而 8.9.68 及以下默认的 config.json 中未包含这些参数，启动时会报错。按照 lookme.txt 补全就好了。
建议同步补全所有的 config.json 中的新增参数。否则小白会懵逼 😵

![screenshot (1)](https://github.com/fuqiuluo/unidbg-fetch-qsign/assets/3938353/4f3005b9-7298-4a6c-9e40-34e61644e887)
![screenshot (2)](https://github.com/fuqiuluo/unidbg-fetch-qsign/assets/3938353/3c48d735-f86d-4438-a180-c8864383c423)

**Comment by callng** [comment]
fixed
