### ISSUE TITLE
linux部署完qsign签名服务器后，本地开gocq，qq里向机器人发送了命令，gocq显示机器人已回复，但是qq上为什么没收到

### ISSUE THREAD

**Issue by k62011128** [fuqiuluo/unidbg-fetch-qsign#254]
### Discussed in https://github.com/fuqiuluo/unidbg-fetch-qsign/discussions/253

<div type='discussions-op-text'>

<sup>Originally posted by **k62011128** September 17, 2023</sup>
linux服务器最后一段日志如下，kanami是我主机名

**Sep 17 16:28:43 kanami env[2248]: File closed '/dev/urandom' from RX@0x40a8ece4[libc.so]0x1ece4
Sep 17 16:28:43 kanami env[2248]: File opened '/dev/urandom' with oflags=0x0 from RX@0x40a92854[libc.so]0x22854
Sep 17 16:28:43 kanami env[2248]: Read 4 bytes from '/dev/urandom'
Sep 17 16:28:43 kanami env[2248]: File closed '/dev/urandom' from RX@0x40a8ece4[libc.so]0x1ece4
Sep 17 16:28:43 kanami env[2248]: File opened '/dev/urandom' with oflags=0x0 from RX@0x40a92854[libc.so]0x22854
Sep 17 16:28:43 kanami env[2248]: Read 4 bytes from '/dev/urandom'
Sep 17 16:28:43 kanami env[2248]: File closed '/dev/urandom' from RX@0x40a8ece4[libc.so]0x1ece4
Sep 17 16:28:43 kanami env[2248]: File opened '/dev/urandom' with oflags=0x0 from RX@0x40a92854[libc.so]0x22854
Sep 17 16:28:43 kanami env[2248]: Read 4 bytes from '/dev/urandom'
Sep 17 16:28:43 kanami env[2248]: File closed '/dev/urandom' from RX@0x40a8ece4[libc.so]0x1ece4
Sep 17 16:28:43 kanami env[2248]: File opened '/dev/urandom' with oflags=0x0 from RX@0x40a92854[libc.so]0x22854
Sep 17 16:28:43 kanami env[2248]: Read 4 bytes from '/dev/urandom'
Sep 17 16:28:43 kanami env[2248]: File closed '/dev/urandom' from RX@0x40a8ece4[libc.so]0x1ece4
Sep 17 16:28:43 kanami env[2248]: File closed '/dev/urandom' from RX@0x40a8ece4[libc.so]0x1ece4
Sep 17 16:28:43 kanami env[2248]: Accept static com/tencent/mobileqq/dt/model/FEBound->transform(I[B)[B
Sep 17 16:28:43 kanami env[2248]: JNIEnv->GetStaticMethodID(com/tencent/mobileqq/dt/model/FEBound.transform(I[B)[B) => 0x5291e1c4 was called from RX@0x403>
Sep 17 16:28:43 kanami env[2248]: JNIEnv->NewByteArray(41) was called from RX@0x401cc2f4[libfekit.so]0x1cc2f4
Sep 17 16:28:43 kanami env[2248]: JNIEnv->SetByteArrayRegion([B@6658b218, 0, 41, RW@0x40c13750) was called from RX@0x401cc330[libfekit.so]0x1cc330
Sep 17 16:28:43 kanami env[2248]: JNIEnv->CallStaticObjectMethodV(class com/tencent/mobileqq/dt/model/FEBound, transform(0x2, [B@6658b218) => [B@e3a0da5) >
Sep 17 16:28:43 kanami env[2248]: JNIEnv->GetArrayLength([B@e3a0da5 => 41) was called from RX@0x401cc360[libfekit.so]0x1cc360
Sep 17 16:28:43 kanami env[2248]: File opened '/dev/urandom' with oflags=0x0 from RX@0x40a92854[libc.so]0x22854
Sep 17 16:28:43 kanami env[2248]: Read 4 bytes from '/dev/urandom'
Sep 17 16:28:43 kanami env[2248]: File closed '/dev/urandom' from RX@0x40a8ece4[libc.so]0x1ece4
Sep 17 16:28:43 kanami env[2248]: File closed '/dev/urandom' from RX@0x40a8ece4[libc.so]0x1ece4
Sep 17 16:28:43 kanami env[2248]: JNIEnv->NewByteArray(48) was called from RX@0x400b32fc[libfekit.so]0xb32fc
Sep 17 16:28:43 kanami env[2248]: JNIEnv->SetByteArrayRegion([B@3afda06f, 0, 48, RW@0x40c11000) was called from RX@0x400b3438[libfekit.so]0xb3438
Sep 17 16:28:43 kanami env[2248]: JNIEnv->ReleaseStringUTFChars("MessageSvc.PbSendMsg") was called from RX@0x403a25b8[libfekit.so]0x3a25b8
Sep 17 16:28:43 kanami env[2248]: JNIEnv->SetObjectField(com.tencent.mobileqq.sign.QQSecuritySign$SignResult@49f52439, sign [B => [B@3afda06f) was called >
Sep 17 16:28:43 kanami env[2248]: JNIEnv->ReleaseStringUTFChars("V1_AND_SQ_8.9.63_4194_YYB_D") was called from RX@0x4016a0a0[libfekit.so]0x16a0a0
Sep 17 16:28:43 kanami env[2248]: JNIEnv->ReleaseStringUTFChars("MessageSvc.PbSendMsg") was called from RX@0x4016a0b8[libfekit.so]0x16a0b8
Sep 17 16:28:43 kanami env[2248]: JNIEnv->ReleaseStringUTFChars("1092545386") was called from RX@0x4016a0e4[libfekit.so]0x16a0e4
lines 971-1001/1001 (END)**

gocq显示如下

**[2023-09-17 16:28:42] [INFO]: 收到好友 紫水晶(200000087) 的消息: echo hi (516429343)
[2023-09-17 16:28:43] [INFO]: 发送好友 200000087(200000087)  的消息: [{"type":  ... (-72406757)**

我用windows本地部署的签名服务器是有效的，linux是1核2g的
</div>

**Comment by k62011128** [comment]
用的是8.9.71版本的

**Comment by k62011128** [comment]
奇怪的是在机器人发送群消息时，会显示”群消息发送失败，账号可能被风控“，而我windows本地开签名服务器，机器人账号是能发消息的

**Comment by fuqiuluo** [comment]
No collaboration
