### ISSUE TITLE
服务器过程运行出现异常

### ISSUE THREAD

**Issue by Xiaolangs** [fuqiuluo/unidbg-fetch-qsign#257]
只能进行服务重启才可恢复 
使用版本1.2.1
txlib:8.9.73
日志
io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invokeSuspend(NettyApplicationCallHandler.kt:119)
Sep 21 17:09:28 mail.bt.cn env[3237]: at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
Sep 21 17:09:28 mail.bt.cn env[3237]: at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
Sep 21 17:09:28 mail.bt.cn env[3237]: at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
Sep 21 17:09:28 mail.bt.cn env[3237]: at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
Sep 21 17:09:28 mail.bt.cn env[3237]: at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
Sep 21 17:09:28 mail.bt.cn env[3237]: at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
Sep 21 17:09:28 mail.bt.cn env[3237]: at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
Sep 21 17:09:28 mail.bt.cn env[3237]: at io.ktor.server.netty.NettyApplicationCallHandler.handleRequest(NettyApplicationCallHandler.kt:37)
Sep 21 17:09:28 mail.bt.cn env[3237]: at io.ktor.server.netty.NettyApplicationCallHandler.channelRead(NettyApplicationCallHandler.kt:29)
Sep 21 17:09:28 mail.bt.cn env[3237]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
Sep 21 17:09:28 mail.bt.cn env[3237]: at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)
Sep 21 17:09:28 mail.bt.cn env[3237]: at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:425)
Sep 21 17:09:28 mail.bt.cn env[3237]: at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
Sep 21 17:09:28 mail.bt.cn env[3237]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
Sep 21 17:09:28 mail.bt.cn env[3237]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
Sep 21 17:09:28 mail.bt.cn env[3237]: at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
Sep 21 17:09:28 mail.bt.cn env[3237]: at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
Sep 21 17:09:28 mail.bt.cn env[3237]: at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
Sep 21 17:09:28 mail.bt.cn env[3237]: at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda$1$lambda$0(NettyApplicationEngine.kt:296)
Sep 21 17:09:28 mail.bt.cn env[3237]: at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
Sep 21 17:09:28 mail.bt.cn env[3237]: at java.lang.Thread.run(Thread.java:748)
Sep 21 17:10:02 mail.bt.cn env[3237]: moe.fuqiuluo.api.MissingKeyError: First use must be submitted with android_id and guid.
Sep 21 17:10:02 mail.bt.cn env[3237]: at moe.fuqiuluo.api.MissingKeyError.<clinit>(exceptions.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at moe.fuqiuluo.api.QsignKt.requestSign(qsign.kt:70)
Sep 21 17:10:02 mail.bt.cn env[3237]: at moe.fuqiuluo.api.QsignKt.access$requestSign(qsign.kt:1)
Sep 21 17:10:02 mail.bt.cn env[3237]: at moe.fuqiuluo.api.QsignKt$sign$2.invokeSuspend(qsign.kt:45)
Sep 21 17:10:02 mail.bt.cn env[3237]: at moe.fuqiuluo.api.QsignKt$sign$2.invoke(qsign.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at moe.fuqiuluo.api.QsignKt$sign$2.invoke(qsign.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.routing.Route$buildPipeline$1$1.invokeSuspend(Route.kt:116)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.routing.Route$buildPipeline$1$1.invoke(Route.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.routing.Route$buildPipeline$1$1.invoke(Route.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invoke(Pipeline.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invoke(Pipeline.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.routing.Routing.executeResult(Routing.kt:190)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.routing.Routing.interceptor(Routing.kt:64)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.routing.Routing$Plugin$install$1.invokeSuspend(Routing.kt:140)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.routing.Routing$Plugin$install$1.invoke(Routing.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.routing.Routing$Plugin$install$1.invoke(Routing.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invokeSuspend(BaseApplicationEngine.kt:124)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invoke(BaseApplicationEngine.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invoke(BaseApplicationEngine.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.application.hooks.CallFailed$install$1$1.invokeSuspend(CommonHooks.kt:45)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.application.hooks.CallFailed$install$1$1.invoke(CommonHooks.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.application.hooks.CallFailed$install$1$1.invoke(CommonHooks.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
Sep 21 17:10:02 mail.bt.cn env[3237]: at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.application.hooks.CallFailed$install$1.invokeSuspend(CommonHooks.kt:44)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.application.hooks.CallFailed$install$1.invoke(CommonHooks.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.application.hooks.CallFailed$install$1.invoke(CommonHooks.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invokeSuspend(DefaultEnginePipeline.kt:118)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invoke(DefaultEnginePipeline.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invoke(DefaultEnginePipeline.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invokeSuspend(NettyApplicationCallHandler.kt:119)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
Sep 21 17:10:02 mail.bt.cn env[3237]: at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
Sep 21 17:10:02 mail.bt.cn env[3237]: at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
Sep 21 17:10:02 mail.bt.cn env[3237]: at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
Sep 21 17:10:02 mail.bt.cn env[3237]: at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.netty.NettyApplicationCallHandler.handleRequest(NettyApplicationCallHandler.kt:37)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.netty.NettyApplicationCallHandler.channelRead(NettyApplicationCallHandler.kt:29)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:425)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda$1$lambda$0(NettyApplicationEngine.kt:296)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
Sep 21 17:10:02 mail.bt.cn env[3237]: at java.lang.Thread.run(Thread.java:748)
Sep 21 17:10:02 mail.bt.cn env[3237]: moe.fuqiuluo.api.MissingKeyError: First use must be submitted with android_id and guid.
Sep 21 17:10:02 mail.bt.cn env[3237]: at moe.fuqiuluo.api.MissingKeyError.<clinit>(exceptions.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at moe.fuqiuluo.api.QsignKt.requestSign(qsign.kt:70)
Sep 21 17:10:02 mail.bt.cn env[3237]: at moe.fuqiuluo.api.QsignKt.access$requestSign(qsign.kt:1)
Sep 21 17:10:02 mail.bt.cn env[3237]: at moe.fuqiuluo.api.QsignKt$sign$2.invokeSuspend(qsign.kt:45)
Sep 21 17:10:02 mail.bt.cn env[3237]: at moe.fuqiuluo.api.QsignKt$sign$2.invoke(qsign.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at moe.fuqiuluo.api.QsignKt$sign$2.invoke(qsign.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.routing.Route$buildPipeline$1$1.invokeSuspend(Route.kt:116)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.routing.Route$buildPipeline$1$1.invoke(Route.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.routing.Route$buildPipeline$1$1.invoke(Route.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invoke(Pipeline.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.routing.Routing$executeResult$$inlined$execute$1.invoke(Pipeline.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.routing.Routing.executeResult(Routing.kt:190)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.routing.Routing.interceptor(Routing.kt:64)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.routing.Routing$Plugin$install$1.invokeSuspend(Routing.kt:140)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.routing.Routing$Plugin$install$1.invoke(Routing.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.routing.Routing$Plugin$install$1.invoke(Routing.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invokeSuspend(BaseApplicationEngine.kt:124)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invoke(BaseApplicationEngine.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.engine.BaseApplicationEngineKt$installDefaultTransformationChecker$1.invoke(BaseApplicationEngine.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.application.hooks.CallFailed$install$1$1.invokeSuspend(CommonHooks.kt:45)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.application.hooks.CallFailed$install$1$1.invoke(CommonHooks.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.application.hooks.CallFailed$install$1$1.invoke(CommonHooks.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
Sep 21 17:10:02 mail.bt.cn env[3237]: at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.application.hooks.CallFailed$install$1.invokeSuspend(CommonHooks.kt:44)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.application.hooks.CallFailed$install$1.invoke(CommonHooks.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.application.hooks.CallFailed$install$1.invoke(CommonHooks.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invokeSuspend(DefaultEnginePipeline.kt:118)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invoke(DefaultEnginePipeline.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$1.invoke(DefaultEnginePipeline.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invokeSuspend(Pipeline.kt:478)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1$invokeSuspend$$inlined$execute$1.invoke(Pipeline.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.util.debug.ContextUtilsKt.initContextInDebugMode(ContextUtils.kt:17)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invokeSuspend(NettyApplicationCallHandler.kt:119)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
Sep 21 17:10:02 mail.bt.cn env[3237]: at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:44)
Sep 21 17:10:02 mail.bt.cn env[3237]: at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
Sep 21 17:10:02 mail.bt.cn env[3237]: at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
Sep 21 17:10:02 mail.bt.cn env[3237]: at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
Sep 21 17:10:02 mail.bt.cn env[3237]: at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.netty.NettyApplicationCallHandler.handleRequest(NettyApplicationCallHandler.kt:37)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.netty.NettyApplicationCallHandler.channelRead(NettyApplicationCallHandler.kt:29)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:61)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:425)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda$1$lambda$0(NettyApplicationEngine.kt:296)
Sep 21 17:10:02 mail.bt.cn env[3237]: at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
Sep 21 17:10:02 mail.bt.cn env[3237]: at java.lang.Thread.run(Thread.java:748)
Sep 21 17:10:22 mail.bt.cn systemd[1]: Stopping unidbg-fetch-qsign...

**Comment by xszqxszq** [comment]
+1，我登了多个账号，好像是有账号冻结就会出现这个，但是会导致其他没冻结的账号也无法使用服务了，必须手动重启

**Comment by Xiaolangs** [comment]
> +1，我登了多个账号，好像是有账号冻结就会出现这个，但是会导致其他没冻结的账号也无法使用服务了，必须手动重启 upd: 没冻结也会出现这个，不知道为什么

我就登录一个号，大概一小时左右就会这样，机器人也不会退出登录只有签名服务有问题，签名服务重启还要手动重启机器人的服务重新登录

**Comment by Xiaolangs** [comment]
好像跟消息发送太频繁有关系 消息间隔太短

**Comment by ability66** [comment]
+1，想知道有没有什么好的办法，比如写个脚本看进程没了就重启？

**Comment by Xiaolangs** [comment]
> +1，想知道有没有什么好的办法，比如写个脚本看进程没了就重启？

只重启qsign服务还不行 连机器人都要重新登录才行

**Comment by ability66** [comment]
不知道，我今天刚刚把机器人部署到服务器上，然后过了几个小时qsign就寄了，不知道该怎么办，不然每次都要手动重连

**Comment by XY0797** [comment]
+1，每隔40分钟就会崩溃，这个和消息频繁程度无关
我已经放弃最新版本了，使用1.1.9没有这个问题

**Comment by Xiaolangs** [comment]
> +1，每隔40分钟就会崩溃，这个和消息频繁程度无关 我已经放弃最新版本了，使用1.1.9没有这个问题

我使用1.1.9也有同样问题

**Comment by fuqiuluo** [comment]
使用脚本每隔一段时间请求，失败就重新启动，这个唯一的办法了，目前tx最新版本已经把unidbg给检测死了，
```c++
#include <jni.h>
#include <string>
#include <utility>
#include <sys/auxv.h>

uint64_t hwcapsByAsm() {
    uint64_t value;
    asm volatile("mrs %[result], ID_AA64PFR0_EL1 "
                : [result] "=r"(value));
    return value;
}

extern "C"
JNIEXPORT jstring JNICALL
Java_moe_protocol_servlet_utils_PlatformUtils_outCpuInfo(JNIEnv *env, jobject thiz) {
    unsigned long hwcaps = getauxval(AT_HWCAP);//可以使用hwcapsByAsm替代
    int i;
    char *list[32] = {"fp", "asimd", "evtstrm", "aes", "pmull", "sha1",
                      "sha2", "crc32", "atomics", "fphp", "asimdhp",
                      "cpuid", "asimdrdm","jscvt", "fcma", "lrcpc",
                      "dcpop", "sha3", "sm3", "sm4", "asimddp" ,
                      "sha512", "sve", "asimdfhm", "dit", "uscat",
                      "ilrcpc", "flagm", "ssbs", "sb", "paca","pacg",};
    std::string out;
    out += "flags: "; // unidbg返回空
    for (i = 0; i< 32; i++){
        if (hwcaps & BIT_SHIFTS(i)) {
            out += list[i];
            out += ", ";
        }
    }
   
   // 读取/proc/cpuinfo文件对比3个地方（辅助向量/getaux.../cpuinfo）出来的flags，对比，即可检测unidbg。

    return env->NewStringUTF(out.c_str());
}
```

**Comment by fuqiuluo** [comment]
目前建议使用shamrock，进行真机hook开放api
