### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by touchscale** [fuqiuluo/unidbg-fetch-qsign#263]
错误: 找不到或无法加载主类 MainKt
原因: java.lang.ClassNotFoundException: MainKt![IMG_20230922_113202.jpg](https://github.com/fuqiuluo/unidbg-fetch-qsign/assets/107158734/f2893b7c-3219-4422-99e3-cf567980cd99)

**Comment by tqlnb** [comment]
一样

**Comment by tqlnb** [comment]
回退到之前版本可以用

**Comment by touchscale** [comment]
嗯，1.1.9是正常的

**Comment by fuqiuluo** [comment]
发release的人发错了，正在推送新的代码，主分支奇奇怪怪什么妖魔鬼怪都有，https://github.com/fuqiuluo/unidbg-fetch-qsign/actions/runs/6284578213
