### ISSUE TITLE
安全性建议

### ISSUE THREAD

**Issue by fuqiuluo** [fuqiuluo/unidbg-fetch-qsign#268]
使用[Shamrock](https://github.com/linxinrao/Shamrock)在xposed中开启`专业级API`选项，在qq中登录一次后，不需要保持上线状态，即可获得稳定安全的sign调用，Shamrock的sign调用参数和qsign一致，除`fix-protocol-plugin`以外，大多数项目已经支持使用。

> 注意：优先建议使用LSPosed，在VXP与edxp的测试中遇到了不可抗力的错误，导致模块无法使用！没有root的用户可以尝试在安卓9以上版本使用LSPatch（依旧需要安装shamrock本体）。

**Comment by Zyy955** [comment]
好耶！
