### ISSUE TITLE
docker-compose启动时 报JAVA_HOME的环境变量不对

### ISSUE THREAD

**Issue by GithubCin** [fuqiuluo/unidbg-fetch-qsign#33]
因为没找到docker镜像的仓库，只好在这里提了

@XZhouQD

环境是win10 使用的docker-compose,yml如下

`version: '3'
services:
  qsign:
    image: xzhouqd/qsign:8.9.63
    ports:
      - "9111:8080"
    environment:
      - PORT=8080
      - COUNT=3
      - ANDROID_ID=3b326e0-----
    container_name: qsign
    restart: always`

`PS E:\sign> docker-compose up
Recreating qsign ... done
Attaching to qsign
qsign    | Using port 8080, count 3, android_id 3b32--------
qsign    |
qsign    | ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
qsign    |
qsign    | Please set the JAVA_HOME variable in your environment to match the
qsign    | location of your Java installation.
qsign    |
qsign exited with code 1`

**Comment by XZhouQD** [comment]
docker镜像是linux/amd64，然后请尝试升级下你的docker-engine，如果还是不行，那就是win确实用不了
