### ISSUE TITLE
arm64    1.0.5 启动失败

### ISSUE THREAD

**Issue by mmmjie** [fuqiuluo/unidbg-fetch-qsign#41]
环境ubuntu22.04  arm64  
openjdk version "19.0.2" 2023-01-17
OpenJDK Runtime Environment (build 19.0.2+7-Ubuntu-0ubuntu322.04)
OpenJDK 64-Bit Server VM (build 19.0.2+7-Ubuntu-0ubuntu322.04, mixed mode, sharing)

运行1.0.4可以，但1.0.5不行

ubuntu@mjie:~/qsign/1.0.5$ bash bin/unidbg-fetch-qsign --port=26004 --count=1 --library=/home/ubuntu/qsign/library/8.9.53 --android_id=761012a4d3d74e5a
17:22:12.360 [main] INFO Main - Unidbg workerCount: 1
17:22:12.364 [main] INFO Main - Debug enable: false
17:22:12.368 [main] DEBUG org.scijava.nativelib.NativeLibraryUtil - processor is AARCH_64 os.arch is aarch64
17:22:12.368 [main] DEBUG org.scijava.nativelib.NativeLibraryUtil - architecture is LINUX_ARM64 os.name is linux
17:22:12.370 [WorkerPool: MainKt$$Lambda$17/0x0000000801017b20@387c703b] INFO Main - Try to construct QSignWorker.
17:22:12.386 [WorkerPool: MainKt$$Lambda$17/0x0000000801017b20@387c703b] DEBUG org.scijava.nativelib.BaseJniExtractor - Deleting leftover folder: /tmp/nativelib-loader_5314229837086467268
17:22:12.412 [WorkerPool: MainKt$$Lambda$17/0x0000000801017b20@387c703b] DEBUG org.scijava.nativelib.NativeLibraryUtil - architecture is LINUX_ARM64 os.name is linux
17:22:12.413 [WorkerPool: MainKt$$Lambda$17/0x0000000801017b20@387c703b] DEBUG org.scijava.nativelib.NativeLibraryUtil - architecture is LINUX_ARM64 os.name is linux
17:22:12.413 [WorkerPool: MainKt$$Lambda$17/0x0000000801017b20@387c703b] DEBUG org.scijava.nativelib.NativeLibraryUtil - platform specific path is natives/linux_arm64/
17:22:12.413 [WorkerPool: MainKt$$Lambda$17/0x0000000801017b20@387c703b] DEBUG org.scijava.nativelib.BaseJniExtractor - mappedLib is libdynarmic.so
17:22:12.414 [WorkerPool: MainKt$$Lambda$17/0x0000000801017b20@387c703b] DEBUG org.scijava.nativelib.BaseJniExtractor - Couldn't find resource natives/linux_arm64/libdynarmic.so
17:22:12.414 [WorkerPool: MainKt$$Lambda$17/0x0000000801017b20@387c703b] DEBUG org.scijava.nativelib.NativeLibraryUtil - platform specific path is linux_arm64/
17:22:12.414 [WorkerPool: MainKt$$Lambda$17/0x0000000801017b20@387c703b] DEBUG org.scijava.nativelib.BaseJniExtractor - mappedLib is libdynarmic.so
17:22:12.415 [WorkerPool: MainKt$$Lambda$17/0x0000000801017b20@387c703b] DEBUG org.scijava.nativelib.BaseJniExtractor - Couldn't find resource linux_arm64/libdynarmic.so
17:22:12.415 [WorkerPool: MainKt$$Lambda$17/0x0000000801017b20@387c703b] DEBUG org.scijava.nativelib.NativeLibraryUtil - platform specific path is META-INF/lib/linux_arm64/
17:22:12.415 [WorkerPool: MainKt$$Lambda$17/0x0000000801017b20@387c703b] DEBUG org.scijava.nativelib.BaseJniExtractor - mappedLib is libdynarmic.so
17:22:12.415 [WorkerPool: MainKt$$Lambda$17/0x0000000801017b20@387c703b] DEBUG org.scijava.nativelib.BaseJniExtractor - Couldn't find resource META-INF/lib/linux_arm64/libdynarmic.so
17:22:12.416 [WorkerPool: MainKt$$Lambda$17/0x0000000801017b20@387c703b] DEBUG org.scijava.nativelib.NativeLibraryUtil - architecture is LINUX_ARM64 os.name is linux
17:22:12.417 [WorkerPool: MainKt$$Lambda$17/0x0000000801017b20@387c703b] DEBUG org.scijava.nativelib.NativeLibraryUtil - architecture is LINUX_ARM64 os.name is linux
17:22:12.417 [WorkerPool: MainKt$$Lambda$17/0x0000000801017b20@387c703b] DEBUG org.scijava.nativelib.NativeLibraryUtil - platform specific path is natives/linux_arm64/
17:22:12.417 [WorkerPool: MainKt$$Lambda$17/0x0000000801017b20@387c703b] DEBUG org.scijava.nativelib.BaseJniExtractor - mappedLib is libkvm.so
17:22:12.418 [WorkerPool: MainKt$$Lambda$17/0x0000000801017b20@387c703b] DEBUG org.scijava.nativelib.BaseJniExtractor - URL is jar:file:/home/ubuntu/qsign/1.0.5/lib/unidbg-fix.jar!/natives/linux_arm64/libkvm.so
17:22:12.418 [WorkerPool: MainKt$$Lambda$17/0x0000000801017b20@387c703b] DEBUG org.scijava.nativelib.BaseJniExtractor - URL path is file:/home/ubuntu/qsign/1.0.5/lib/unidbg-fix.jar!/natives/linux_arm64/libkvm.so
17:22:12.419 [WorkerPool: MainKt$$Lambda$17/0x0000000801017b20@387c703b] DEBUG org.scijava.nativelib.BaseJniExtractor - Extracting 'jar:file:/home/ubuntu/qsign/1.0.5/lib/unidbg-fix.jar!/natives/linux_arm64/libkvm.so' to '/tmp/nativelib-loader_3218553239318154513/libkvm.so'
open /dev/kvm failed.
Aborted (core dumped)

**Comment by fuqiuluo** [comment]
https://github.com/fuqiuluo/unidbg-fetch-qsign/discussions/20
