### ISSUE TITLE
运行一会就会爆内存

### ISSUE THREAD

**Issue by hakureireimusama** [fuqiuluo/unidbg-fetch-qsign#44]
## 问题咨询、讨论，请在 [Discussions](../discussions) 发帖。issues 仅用于提交 Bug。
![1](https://github.com/fuqiuluo/unidbg-fetch-qsign/assets/49976244/2a6fae8f-4f0f-4ff0-a64b-020a0c475058)
![2](https://github.com/fuqiuluo/unidbg-fetch-qsign/assets/49976244/e018af18-a174-429d-acdf-b74fbb4afeae)
![3](https://github.com/fuqiuluo/unidbg-fetch-qsign/assets/49976244/ff4c4dc1-905b-48f6-a6fe-422d81415ee3)

下的1.0.5的版本会一直这样刷屏刷一会内存就满了，我内存16G，sever2022，java8
换个问题应该要怎么解决呀~

**Comment by HMScygnet** [comment]
我也是，挂着不用也会内存泄漏

**Comment by hakureireimusama** [comment]
还会生成一个10G以上的文件

**Comment by shionagisa** [comment]
我目前是每4小时定时重启qsign解决

**Comment by eya46** [comment]
![QQ截图20230629094825](https://github.com/fuqiuluo/unidbg-fetch-qsign/assets/61458340/2ec57abc-78f1-45fc-9be7-190da6b68d20)
有没要碰到爆硬盘的...，前天20点部署后就莫名其妙出现这个

**Comment by ayakasuki** [comment]
我直接是docker那边限制他256MB了

**Comment by SunshineboyZj** [comment]
TCP连接数呈上升趋势
![image](https://github.com/fuqiuluo/unidbg-fetch-qsign/assets/81549837/bcc554f1-b762-4f08-a7eb-f05d5f45af12)

**Comment by hakureireimusama** [comment]
> ![QQ截图20230629094825](https://user-images.githubusercontent.com/61458340/249651243-2ec57abc-78f1-45fc-9be7-190da6b68d20.png) 有没要碰到爆硬盘的...，前天20点部署后就莫名其妙出现这个

遇到了https://github.com/fuqiuluo/unidbg-fetch-qsign/issues/44#issuecomment-1611717965

**Comment by fuqiuluo** [comment]
调整GC策略，定时重启。

**Comment by eya46** [comment]
我现在内存改成256mb限制，然后定时1小时重启，看看之后啥情况

**Comment by TheTychoStar** [comment]
运行没一会儿系统就卡死了，是不是内存爆了的缘故？跑这个需要多少内存啊？

**Comment by foxwhite25** [comment]
感觉就是内存泄露了，正常来说不应该用这么多

**Comment by foxwhite25** [comment]
> 还会生成一个10G以上的文件 hs_err_pid4012.mdmp

这是 jvm 内存不够 core dump 了，就是把整个内存都丢到硬盘里面让你分析

**Comment by Qian-F** [comment]
所以说这个问题啥时候修（
就是因为这个才一直没敢用: (

**Comment by zangxx66** [comment]
我在非docker环境跑的，count设为1，关闭动态参数，内存很稳定，你们如果是在docker里面跑可以试试非docker环境

**Comment by SunshineboyZj** [comment]
我也是，可能是我内存本就紧张的原因（没开qsign之前已经常态80%+），这几天爆了几次了。
可以把WindowsService2016的Windows Defender关掉了，这玩意至少吃200+MB内存，没啥用，如果内存紧张的可以试试（组策略-计算机配置-管理模板-Windows组件-Windows Defender，把关闭Windows Defender改为已启用就行了），缓解一下压力。
也可以把虚拟内存调大些（听群友说的，不知道有没有用）



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月2日(周日) 凌晨4:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [fuqiuluo/unidbg-fetch-qsign] 运行一会就会爆内存 (Issue #44)




 
我在非docker环境跑的，count设为1，关闭动态参数，内存很稳定，你们如果是在docker里面跑可以试试非docker环境
