### ISSUE TITLE
aarch64 底座的服务器，没有兼容

### ISSUE THREAD

**Issue by YM-Sky** [fuqiuluo/unidbg-fetch-qsign#45]
正常的服务器是没问题的，aarch64 的服务器不行，跑不起来
![image](https://github.com/fuqiuluo/unidbg-fetch-qsign/assets/52541097/6e304a53-890c-4efc-b4f0-7cd0fb9978c5)

**Comment by touale** [comment]
may be you can reCompile for your aarch64  server

**Comment by fuqiuluo** [comment]
https://github.com/fuqiuluo/unidbg-fetch-qsign/discussions/20
