### ISSUE TITLE
Lack of server.host.

### ISSUE THREAD

**Issue by magisk317** [fuqiuluo/unidbg-fetch-qsign#51]
docker启动报错：
```
chatgpt-qq-qsign-1       | Exception in thread "main" java.lang.IllegalArgumentException: Lack of server.host.
chatgpt-qq-qsign-1       | 	at moe.fuqiuluo.comm.ArgsParser.get(ArgsParser.kt:25)
chatgpt-qq-qsign-1       | 	at MainKt.main(Main.kt:45)
```

**Comment by Weltolk** [comment]
> docker启动报错：
> 
> ```
> chatgpt-qq-qsign-1       | Exception in thread "main" java.lang.IllegalArgumentException: Lack of server.host.
> chatgpt-qq-qsign-1       | 	at moe.fuqiuluo.comm.ArgsParser.get(ArgsParser.kt:25)
> chatgpt-qq-qsign-1       | 	at MainKt.main(Main.kt:45)
> ```

readme.md没更新的锅:

https://github.com/search?q=repo%3Afuqiuluo%2Funidbg-fetch-qsign%20Lack%20of%20server.host&type=code

1.0.5版本的启动参数里添加了`--host`参数,用于指定运行在哪个ip上,如果未指定,参数缺少,则会报这个错

如果是想运行在本地,启动参数里添加`--host=127.0.0.1`即可

**Comment by Weltolk** [comment]
> docker启动报错：
> 
> ```
> chatgpt-qq-qsign-1       | Exception in thread "main" java.lang.IllegalArgumentException: Lack of server.host.
> chatgpt-qq-qsign-1       | 	at moe.fuqiuluo.comm.ArgsParser.get(ArgsParser.kt:25)
> chatgpt-qq-qsign-1       | 	at MainKt.main(Main.kt:45)
> ```

缺少`--host`参数
