### ISSUE TITLE
报错 Couldn't find file

### ISSUE THREAD

**Issue by han602938489** [fuqiuluo/unidbg-fetch-qsign#6]
[FEKit_]info: device_token_entry.h:87 initUin 0
[FEKit_]info: device_info.h:583 start create xwid
▒▒▒▒ 27, 2023 8:55:28 ▒▒▒▒ moe.fuqiuluo.unidbg.env.FileResolver resolve
▒▒▒▒: Couldn't find file: /data/user/999
▒▒▒▒ 27, 2023 8:55:28 ▒▒▒▒ com.github.unidbg.linux.ARM64SyscallHandler stat64
▒▒Ϣ: stat64 pathname=/data/user/999
▒▒▒▒ 27, 2023 8:55:28 ▒▒▒▒ moe.fuqiuluo.unidbg.env.FileResolver resolve
▒▒▒▒: Couldn't find file: /data/user/128
▒▒▒▒ 27, 2023 8:55:28 ▒▒▒▒ com.github.unidbg.linux.ARM64SyscallHandler stat64
▒▒Ϣ: stat64 pathname=/data/user/128
▒▒▒▒ 27, 2023 8:55:28 ▒▒▒▒ moe.fuqiuluo.unidbg.env.FileResolver resolve
▒▒▒▒: Couldn't find file: /data/user/10
▒▒▒▒ 27, 2023 8:55:28 ▒▒▒▒ com.github.unidbg.linux.ARM64SyscallHandler stat64
▒▒Ϣ: stat64 pathname=/data/user/10
▒▒▒▒ 27, 2023 8:55:28 ▒▒▒▒ moe.fuqiuluo.unidbg.env.FileResolver resolve
▒▒▒▒: Couldn't find file: /data/user/11
这个报错怎么解决 win10系统

**Comment by fuqiuluo** [comment]
可无视
