### ISSUE TITLE
1.1gocq 一发消息就崩溃

### ISSUE THREAD

**Issue by mmmjie** [fuqiuluo/unidbg-fetch-qsign#65]
如果签名进程崩溃后重启，gocq没有同步重启的话，gocq一发消息签名进程直接崩溃
ubuntu22.04
arm64

**Comment by mmmjie** [comment]
[hs_err_pid1707581.log](https://github.com/fuqiuluo/unidbg-fetch-qsign/files/11912525/hs_err_pid1707581.log)

**Comment by fuqiuluo** [comment]
在 https://github.com/fuqiuluo/unidbg-fetch-qsign/releases/tag/1.1.5 版本修复
