### ISSUE TITLE
ARM64架构运行下，在接收到sign请求时程序直接崩溃

### ISSUE THREAD

**Issue by ThirdBlood** [fuqiuluo/unidbg-fetch-qsign#70]
这是日志文件：  
[hs_err_pid242513.log](https://github.com/fuqiuluo/unidbg-fetch-qsign/files/11915520/hs_err_pid242513.log)  
这是我使用的启动命令：  
`bash bin/unidbg-fetch-qsign --host=127.0.0.1 --port=8081 --count=2 --library=txlib/8.9.63 --android_id=4a5ca761efff304d`

**Comment by fuqiuluo** [comment]
在 https://github.com/fuqiuluo/unidbg-fetch-qsign/releases/tag/1.1.5 版本修复
