### ISSUE TITLE
貌似每天下午6点会自动结束进程

### ISSUE THREAD

**Issue by ElainaFanBoy** [fuqiuluo/unidbg-fetch-qsign#76]
不知道咋回事，每天下午大概五六点的样子，进程会自己关闭

**Comment by ilihu** [comment]
麻烦汇报一下，操作系统，平台类型(x86,arm?)，jdk(jre)版本，oracle的，还是open的，以及版本
这样方便复现

**Comment by ElainaFanBoy** [comment]
> 麻烦汇报一下，操作系统，平台类型(x86,arm?)，jdk(jre)版本，oracle的，还是open的，以及版本 这样方便复现

Windows 10 家庭中文版 22H2，X86
IMPLEMENTOR="Oracle Corporation"
JAVA_VERSION="18.0.2.1"

**Comment by rhwong** [comment]
保存为ps1文件，然后右键用powershell运行。api不可用时自动启动。
```
$url = "http://127.0.0.1:8080"

while ($true) {
    try {
        $request = [System.Net.HttpWebRequest]::Create($url)
        $request.Method = "HEAD"
        $request.Timeout = 5000
        
        $response = $request.GetResponse()
        $statusCode = [int]$response.StatusCode
        
        if ($statusCode -eq 200 -or ($statusCode -ge 400 -and $statusCode -le 405)) {
            Write-Host "Qsign API 状态正常."
        }
        
        $response.Close()
    } catch [System.Net.WebException] {
        $statusCode = [int]$_.Exception.Response.StatusCode
        
        if ($statusCode -eq 405 -or ($statusCode -ge 400 -and $statusCode -le 405)) {
            Write-Host "Qsign API 状态正常."
        } else {
            Write-Host "检测到Qsign API已离线，正在重启程序..."
            
            # 启动项目
            # 这里改成你自己的启动脚本或者是启动的快捷方式
            Start D:\qsign\1.1.0\bin\qsign.lnk
            
            Write-Host "Qsign服务端已启动."
        }
    }
    
    # 等待一段时间后继续监测
    Start-Sleep -Seconds 5
}

```

**Comment by ElainaFanBoy** [comment]
> 保存为ps1文件，然后右键用powershell运行。api不可用时自动启动。
> 
> ```
> $url = "http://127.0.0.1:8880"
> 
> while ($true) {
>     try {
>         $request = [System.Net.HttpWebRequest]::Create($url)
>         $request.Method = "HEAD"
>         $request.Timeout = 5000
>         $response = $request.GetResponse()
>     } catch [System.Net.WebException] {
>         $statusCode = [int]$_.Exception.Response.StatusCode
>         
>         if ($statusCode -eq 200 -or ($statusCode -ge 400 -and $statusCode -le 405)) {
>             Write-Host "Qsign API 状态正常."
>         } else {
>             Write-Host "检测到Qsign API已离线，正在重启程序..."
>             
>             # 启动项目(这里替换成你自己的启动脚本或快捷方式路径)
>             Start D:\qsign\1.1.0\bin\qsign.lnk
>             
>             Write-Host "Qsign服务端已启动."
>         }
>     }
>     
>     # 等待一段时间后继续监测
>     Start-Sleep -Seconds 5
> }
> ```

请问第一行的url需要改为qsign自己设置的端口吗

**Comment by ElainaFanBoy** [comment]
> > 保存为ps1文件，然后右键用powershell运行。api不可用时自动启动。
> > ```
> > $url = "http://127.0.0.1:8880"
> > 
> > while ($true) {
> >     try {
> >         $request = [System.Net.HttpWebRequest]::Create($url)
> >         $request.Method = "HEAD"
> >         $request.Timeout = 5000
> >         $response = $request.GetResponse()
> >     } catch [System.Net.WebException] {
> >         $statusCode = [int]$_.Exception.Response.StatusCode
> >         
> >         if ($statusCode -eq 200 -or ($statusCode -ge 400 -and $statusCode -le 405)) {
> >             Write-Host "Qsign API 状态正常."
> >         } else {
> >             Write-Host "检测到Qsign API已离线，正在重启程序..."
> >             
> >             # 启动项目(这里替换成你自己的启动脚本或快捷方式路径)
> >             Start D:\qsign\1.1.0\bin\qsign.lnk
> >             
> >             Write-Host "Qsign服务端已启动."
> >         }
> >     }
> >     
> >     # 等待一段时间后继续监测
> >     Start-Sleep -Seconds 5
> > }
> > ```
> 
> 请问第一行的url需要改为qsign自己设置的端口吗

噢，可以了
