### ISSUE TITLE
Windows下有时候会出现运行不正确

### ISSUE THREAD

**Issue by rhwong** [fuqiuluo/unidbg-fetch-qsign#78]
在某一个pc上出现如下故障，API页面显示IAA而不是正常的json返回
java版本
```
java version "1.8.0_333"
Java(TM) SE Runtime Environment (build 1.8.0_333-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.333-b02, mixed mode)
```
![image](https://github.com/fuqiuluo/unidbg-fetch-qsign/assets/58497504/8112820d-30c0-4bdc-aa21-fa7c81e2d5ca)

**Comment by rhwong** [comment]
部分控制台输出
![image](https://github.com/fuqiuluo/unidbg-fetch-qsign/assets/58497504/f0baed71-a471-4784-987d-93cb1e6d5c5e)

**Comment by rhwong** [comment]
但是go-cqhttp在调用签名服务时没有报错。。
![image](https://github.com/fuqiuluo/unidbg-fetch-qsign/assets/58497504/f5371801-56d1-4444-a131-c13a6381aed8)

**Comment by fuqiuluo** [comment]
![image](https://github.com/fuqiuluo/unidbg-fetch-qsign/assets/61898844/c4395636-637e-433d-99ba-4b063d860a3b)

**Comment by fuqiuluo** [comment]
IAA是我写的，更新之后还可以带个云天明

**Comment by rhwong** [comment]
> IAA是我写的，更新之后还可以带个云天明

草。。。我查了半天IAA是什么报错
可是为什么有时候是输出json呢

**Comment by ilihu** [comment]
> > IAA是我写的，更新之后还可以带个云天明
> 
> 草。。。我查了半天IAA是什么报错 可是为什么有时候是输出json呢

1.1.0 之前 / 是json， 1.1.0 改了
