### ISSUE TITLE
8.9.58版本的Android lib和config还有吗

### ISSUE THREAD

**Issue by sadtrain** [fuqiuluo/unidbg-fetch-qsign#99]
如题，现在只剩63和68版本的，我在这个帖子看到的方法已经无法使用
https://mirai.mamoe.net/topic/2348/miraisignhandler-mirai%E5%AF%B9%E6%8E%A5sign%E7%AD%BE%E5%90%8D%E6%9C%8D%E5%8A%A1%E5%99%A8-%E8%A7%A3%E5%86%B3%E7%99%BB%E5%BD%95code-45%E5%A4%B1%E8%B4%A5%E5%92%8C%E7%AD%BE%E5%90%8D%E6%B6%88%E6%81%AF%E5%8F%91%E9%80%81%E9%A3%8E%E6%8E%A7/23?page=2

**Comment by dellbeat** [comment]
lib可以自己从安装包里提，config也是类似，通过反编译找到config的路径再去搜索获取即可，readme.md有简单的介绍。

**Comment by fuqiuluo** [comment]
https://github.com/fuqiuluo/unidbg-fetch-qsign/discussions/84

**Comment by wtmntm114514** [comment]
> lib可以自己从安装包里提，config也是类似，通过反编译找到config的路径再去搜索获取即可，readme.md有简单的介绍。

您好，我反编译看到了qsec/dtconfig.json，但是我到处搜索都没找到相应的地方，这个地方是在哪里呢？

**Comment by dellbeat** [comment]
邮件已收到
